//
// Created by Spencer McKenney on 7/23/18.
//

#ifndef MONGO_C_DRIVER_MONGOC_GRIDFS_PROTOTYPE_DOWNLOAD_STREAM_H
#define MONGO_C_DRIVER_MONGOC_GRIDFS_PROTOTYPE_DOWNLOAD_STREAM_H

#endif //MONGO_C_DRIVER_MONGOC_GRIDFS_PROTOTYPE_DOWNLOAD_STREAM_H
